### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by ghost** [genaller/genal-chat#116]
您好，后端项目启动报如下错误，无法定位错误原因，麻烦指点一下
[6:21:11 PM] Starting compilation in watch mode...

[6:21:15 PM] Found 0 errors. Watching for file changes.

[Nest] 7923   - 08/04/2022, 6:21:16 PM   [NestFactory] Starting Nest application...
[Nest] 7923   - 08/04/2022, 6:21:16 PM   [InstanceLoader] AppModule dependencies initialized +66ms
[Nest] 7923   - 08/04/2022, 6:21:16 PM   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 7923   - 08/04/2022, 6:21:16 PM   [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 7923   - 08/04/2022, 6:21:16 PM   [InstanceLoader] JwtModule dependencies initialized +1ms
[Nest] 7923   - 08/04/2022, 6:21:16 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +81ms
QueryFailedError: ER_INVALID_DEFAULT: Invalid default value for 'username'
    at new QueryFailedError (/usr/local/chat-server/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.<anonymous> (/usr/local/chat-server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:170:45)
    at Query.<anonymous> (/usr/local/chat-server/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/chat-server/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/usr/local/chat-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/chat-server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/chat-server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
[Nest] 7923   - 08/04/2022, 6:21:19 PM   [TypeOrmModule] Unable to connect to the database. Retrying (2)... +3030ms
QueryFailedError: ER_INVALID_DEFAULT: Invalid default value for 'username'
    at new QueryFailedError (/usr/local/chat-server/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.<anonymous> (/usr/local/chat-server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:170:45)
    at Query.<anonymous> (/usr/local/chat-server/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/usr/local/chat-server/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/usr/local/chat-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/local/chat-server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/local/chat-server/node_modules/mysql/lib/protocol/Protocol.js:38:16)

**Comment by cardman007** [comment]
[18:45:44] Starting compilation in watch mode...

node_modules/_@types_prettier@2.7.0@@types/prettier/index.d.ts:41:54 - error TS2315: Type 'IsTuple' is not generic.

41 type IndexProperties<T extends { length: number }> = IsTuple<T> extends true
                                                        ~~~~~~~~~~

node_modules/_@types_prettier@2.7.0@@types/prettier/index.d.ts:53:6 - error TS2456: Type alias 'IsTuple' circularly references itself.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
        ~~~~~~~

node_modules/_@types_prettier@2.7.0@@types/prettier/index.d.ts:53:65 - error TS2574: A rest element type must be an array type.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
                                                                   ~~~~~~~~~~~~~~~

node_modules/_@types_prettier@2.7.0@@types/prettier/index.d.ts:53:84 - error TS2315: Type 'IsTuple' is not generic.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
                                                                                      ~~~~~~~~~~~~~~~

node_modules/_@types_prettier@2.7.0@@types/prettier/index.d.ts:96:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

96     call<


我报这种错。。

**Comment by gislu** [comment]
> 您好，后端项目启动报如下错误，无法定位错误原因，麻烦指点一下 [6:21:11 PM] Starting compilation in watch mode...
> 
> [6:21:15 PM] Found 0 errors. Watching for file changes.
> 
> [Nest] 7923 - 08/04/2022, 6:21:16 PM [NestFactory] Starting Nest application... [Nest] 7923 - 08/04/2022, 6:21:16 PM [InstanceLoader] AppModule dependencies initialized +66ms [Nest] 7923 - 08/04/2022, 6:21:16 PM [InstanceLoader] TypeOrmModule dependencies initialized +1ms [Nest] 7923 - 08/04/2022, 6:21:16 PM [InstanceLoader] PassportModule dependencies initialized +0ms [Nest] 7923 - 08/04/2022, 6:21:16 PM [InstanceLoader] JwtModule dependencies initialized +1ms [Nest] 7923 - 08/04/2022, 6:21:16 PM [TypeOrmModule] Unable to connect to the database. Retrying (1)... +81ms QueryFailedError: ER_INVALID_DEFAULT: Invalid default value for 'username' at new QueryFailedError (/usr/local/chat-server/node_modules/typeorm/error/QueryFailedError.js:11:28) at Query. (/usr/local/chat-server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:170:45) at Query. (/usr/local/chat-server/node_modules/mysql/lib/Connection.js:526:10) at Query._callback (/usr/local/chat-server/node_modules/mysql/lib/Connection.js:488:16) at Query.Sequence.end (/usr/local/chat-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24) at Query.ErrorPacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8) at Protocol._parsePacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/Protocol.js:291:23) at Parser._parsePacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/Parser.js:433:10) at Parser.write (/usr/local/chat-server/node_modules/mysql/lib/protocol/Parser.js:43:10) at Protocol.write (/usr/local/chat-server/node_modules/mysql/lib/protocol/Protocol.js:38:16) [Nest] 7923 - 08/04/2022, 6:21:19 PM [TypeOrmModule] Unable to connect to the database. Retrying (2)... +3030ms QueryFailedError: ER_INVALID_DEFAULT: Invalid default value for 'username' at new QueryFailedError (/usr/local/chat-server/node_modules/typeorm/error/QueryFailedError.js:11:28) at Query. (/usr/local/chat-server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:170:45) at Query. (/usr/local/chat-server/node_modules/mysql/lib/Connection.js:526:10) at Query._callback (/usr/local/chat-server/node_modules/mysql/lib/Connection.js:488:16) at Query.Sequence.end (/usr/local/chat-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24) at Query.ErrorPacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8) at Protocol._parsePacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/Protocol.js:291:23) at Parser._parsePacket (/usr/local/chat-server/node_modules/mysql/lib/protocol/Parser.js:433:10) at Parser.write (/usr/local/chat-server/node_modules/mysql/lib/protocol/Parser.js:43:10) at Protocol.write (/usr/local/chat-server/node_modules/mysql/lib/protocol/Protocol.js:38:16)

数据库报错啊，这不是写着呢，检查下你安装的db配置就行了
