### ISSUE TITLE
关于在树莓派3A+上部署的问题

### ISSUE THREAD

**Issue by 1248680677** [genaller/genal-chat#89]
ERROR  Error loading /home/pi/genal-chat-master/genal-chat-client/vue.config.js:
 ERROR  SyntaxError: Invalid or unexpected token
/home/pi/genal-chat-master/genal-chat-client/node_modules/ajv-keywords/index.js:5
@-webkit-keyframes antCheckboxEffect {
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/pi/genal-chat-master/genal-chat-client/node_modules/webpack/node_modules/schema-utils/src/validateOptions.js:13:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! genal-chat-client@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the genal-chat-client@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-27T10_24_28_723Z-debug.log

编译时报错，不知道如何解决

**Comment by genaller** [comment]
这个错误我也没遇到过。。 可能跟环境有关系？在window运行一次其实很容易
